### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Lis-TV** [nicholas-fr/test-content-validation#1]
1. Propose either add information that  it is supported on Windows only, or update implementation to be possible to run on Linux.
2. Please add information that libxml is also needed.
3. It is worth to clarify the -v folder. For example 'folder containing t1 to t34 subfolders'

**Comment by Lis-TV** [comment]
Propose also make -m optional. If the parameter is skipped, then application shout perform wget to https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/export?format=csv

**Comment by nicholas-fr** [comment]
Thanks for these proposals.

> 1. Propose either add information that  it is supported on Windows only, or update implementation to be possible to run on Linux.

It was intended to work on both Windows and Linux. Following the updates made by Romain, it's confirmed to be now working on Linux as well.

> 2. Please add information that libxml is also needed.

Added to the README and added `requirements.txt`.

> 3. It is worth to clarify the -v folder. For example 'folder containing t1 to t34 subfolders'

Added clarification to the help text:
"Folder containing subfolders with sets of test vectors for a specific codec e.g. "cfhd_sets", that contain subfolders for each frame rate family e.g. "15_30_60", that contain subfolders t1 .. tN with the test vectors to validate. Example of path to
test vector MPD: <vectors>/cfhd_sets/15_30_60/t1/2022-09-23/stream.mpd"

Note that the issues you've had running the tool are mostly due to outdated test vectors, that use an old folder/file structure. The current agreed structure was discussed [here](https://github.com/cta-wave/dpctf-tests/issues/59#issuecomment-981682531) and is:
<media_type>_sets/<sub_media_type (frame_rate_family|audio_codec)>/<stream_id>/<upload_date>
Example: https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/t1/2022-07-20/

> Propose also make -m optional. If the parameter is skipped, then application shout perform wget to https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/export?format=csv

Done (using urllib so it should work on both Windows and Linux).

**Comment by nicholas-fr** [comment]
Thanks for sharing these proposals, I believe these points have been addressed. 
If you have further feedback, please feel free to reopen or to create a new issue.
