### ISSUE TITLE
test_stream_dir incorrectly set

### ISSUE THREAD

**Issue by Lis-TV** [nicholas-fr/test-content-validation#2]
line 353, 
test_stream_dir = Path(str(str(tc_vectors_folder)+'\\'+tc.file_brand[0]+TS_LOCATION_SETS_POST)

The problem is the tc.file_brand[0] does not correspond to the real folder names (avc_sets, caa_sets).
Propose to change the -v call parameter to point to folder with t1..t34 subfolders.

**Comment by nicholas-fr** [comment]
I believe this issue is due to outdated test vectors, that use an old folder/file structure.
The current agreed structure was discussed [here](https://github.com/cta-wave/dpctf-tests/issues/59#issuecomment-981682531) and is:
<media_type>_sets/<sub_media_type (frame_rate_family|audio_codec)>/<stream_id>/<upload_date>

Example: 
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/t1/2022-07-20/

If the folder structure changes again, then I will keep your proposal in mind as a fall back, to ensure the script works.

**Comment by nicholas-fr** [comment]
Thanks for raising this issue, I believe this has been explained/addressed. 
If you have further feedback, please feel free to reopen or create a new issue.
