### ISSUE TITLE
An init.mp4 is not a valid segment name

### ISSUE THREAD

**Issue by Lis-TV** [nicholas-fr/test-content-validation#3]
line 331 - TS_INIT_SEGMENT_NAME = "init.mp4" is not correct.
The names of init segment differs, could be for example croatia_L1_1920x1080@25_60_dash_track1_init.mp4

**Comment by nicholas-fr** [comment]
I believe this issue is due to outdated test vectors, that use an old segment naming convention. 
The current agreed structure was discussed [here](https://github.com/cta-wave/dpctf-tests/issues/59#issuecomment-981682531) and is:
<media_type>_sets/<sub_media_type (frame_rate_family|audio_codec)>/<stream_id>/<upload_date>

Example: 
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/t1/2022-07-20/1/init.mp4

If it turns out that different segment names will be used, then I will update the script to be more flexible.

**Comment by nicholas-fr** [comment]
Thanks for raising this issue, I believe this has been explained/addressed. 
If you have further feedback, please feel free to reopen or create a new issue.
