### ISSUE TITLE
ffmpeg with input mpd does not work (line 453)

### ISSUE THREAD

**Issue by Lis-TV** [nicholas-fr/test-content-validation#6]
There are problems. First, the ffmpeg (v 4.2.7) does not work with mpd

ffmpeg -i WMAS\content\avc_sets\12.5_25_50\t1\2022-01-17\stream.mpd -c:v copy -bsf:v trace_headers -f null -

[dash @ 0000022c89e894c0] Failed to open an initialization section in playlist 0
[dash @ 0000022c89e894c0] Error when loading first fragment, playlist 0
WMAS\content\avc_sets\12.5_25_50\t1\2022-01-17\stream.mpd: No such file or directory

I run it using different approach. I just copied init segment and first data segment to mp4 file, then i run:
copy /B croatia_L1_1920x1080@25_60_dash_track1_init.mp4+croatia_L1_1920x1080@25_60_dash_track1_0.m4s merged.mp4
ffmpeg -i merged.mp4 -c:v copy -bsf:v trace_headers -f null - > report.txt 2>&1

**Comment by nicholas-fr** [comment]
I believe this issue could also be due to outdated test vectors, that use an old folder/file structure, similar to issue #2

Example of current test vector MPD path:
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/t1/2022-07-20/stream.mpd

Running the following command:
`ffmpeg -i stream.mpd -c copy -bsf:v trace_headers -f null - > report.txt 2>&1`
from this folder:
`cfhd_sets/12.5_25_50/t1/2022-07-20/`
which contains `stream.mpd` and where the segments are in the `/1` subfolder, results in the expected report being generated.

**Comment by nicholas-fr** [comment]
Thanks for raising this issue, I believe this has been explained/addressed. 
If you have further feedback, please feel free to reopen or create a new issue.
